name: stable_release

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Release to stable
          body: This is an automated pull request from the main branch to the stable branch.
          commit-message: update changelog
          branch: release-stable
          base: stable
