name: update-flake-lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1,4"

permissions:
  contents: write
  pull-requests: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@4eea0b33e3d1f02ecfe37cf16e7204c424009606 # v3.21.0
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@834c491b2ece4de0bbd00d85214bb5e83b4da5c6 # v28
        with:
          pr-labels: |
            merge-queue
